{"version":3,"file":"ErrorBoundary.js","sourceRoot":"","sources":["../../../../src/containers/ApplicationErrorHandler/ErrorBoundary.tsx"],"names":[],"mappings":";;;;;;;;;;;;;;;;;;;;;;;;;AAAA,6CAAmD;AAEnD,6DAAoE;AAEpE,wCAAuC;AAMvC,SAAS,cAAc,CAAC,EAAwB;QAAtB,KAAK,WAAA;IAC7B,IAAM,WAAW,GAAgB;QAC/B,KAAK,EAAE,sBAAsB;QAC7B,IAAI,EAAE,mBAAmB;QACzB,gBAAgB,EAAE;YAChB;gBAEE,KAAK,EAAE,KAAK,aAAL,KAAK,uBAAL,KAAK,CAAE,OAAO;aACtB;SACF;KACF,CAAC;IACF,OAAO,8BAAC,aAAK,IAAC,KAAK,EAAE,WAAW,GAAI,CAAC;AACvC,CAAC;AAED,IAAM,qBAAqB,GAAG,UAAC,EAAmB;QAAjB,QAAQ,cAAA;IACjC,IAAA,KAAgB,IAAA,gBAAQ,EAAC,CAAC,CAAC,EAA1B,GAAG,QAAA,EAAE,MAAM,QAAe,CAAC;IAElC,IAAA,iBAAS,EAAC;QACR,MAAM,CAAC,UAAC,OAAO,IAAK,OAAA,OAAO,GAAG,CAAC,EAAX,CAAW,CAAC,CAAC;IACnC,CAAC,EAAE,CAAC,QAAQ,CAAC,CAAC,CAAC;IAEf,OAAO,CACL,8BAAC,oCAAa,IAAC,GAAG,EAAE,GAAG,EAAE,cAAc,EAAE,cAAc,IACpD,QAAQ,CACK,CACjB,CAAC;AACJ,CAAC,CAAC;AAEF,kBAAe,qBAAqB,CAAC","sourcesContent":["import React, { useEffect, useState } from 'react';\nimport { ReactNode } from 'react';\nimport { ErrorBoundary, FallbackProps } from 'react-error-boundary';\nimport { ErrorObject } from '../../types';\nimport { Error } from '../Error/Error';\n\ninterface Props {\n  children: ReactNode;\n}\n\nfunction fallbackRender({ error }: FallbackProps) {\n  const ErrorObject: ErrorObject = {\n    title: 'Something went wrong',\n    type: 'application-error',\n    validationErrors: [\n      {\n        // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access\n        title: error?.message,\n      },\n    ],\n  };\n  return <Error error={ErrorObject} />;\n}\n\nconst AsyncApiErrorBoundary = ({ children }: Props) => {\n  const [key, setKey] = useState(0);\n\n  useEffect(() => {\n    setKey((prevKey) => prevKey + 1);\n  }, [children]);\n\n  return (\n    <ErrorBoundary key={key} fallbackRender={fallbackRender}>\n      {children}\n    </ErrorBoundary>\n  );\n};\n\nexport default AsyncApiErrorBoundary;\n"]}